trigger:
- master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\**.*dmg'
      ArtifactName: 'drop'
      publishLocation: 'Container'

        
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\**.*exe'
      ArtifactName: 'drop'
      publishLocation: 'Container'

